-- SQL statements for Supabase table creation and RLS policies

-- ====================================================================================================
-- PROFILES TABLE
-- ====================================================================================================

-- CREATE THE PROFILES TABLE
CREATE TABLE public.profiles (
  id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE,
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  PRIMARY KEY (id)
);

-- ENABLE RLS ON THE PROFILES TABLE
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- POLICY: ALLOW AUTHENTICATED USERS TO SELECT THEIR OWN PROFILE
CREATE POLICY "PUBLIC PROFILES ARE VIEWABLE BY AUTHENTICATED USERS."
  ON public.profiles
  FOR SELECT
  TO AUTHENTICATED
  USING (
    auth.uid() = id
  );

-- POLICY: ALLOW AUTHENTICATED USERS TO INSERT THEIR OWN PROFILE
CREATE POLICY "USERS CAN INSERT THEIR OWN PROFILE."
  ON public.profiles
  FOR INSERT
  TO AUTHENTICATED
  WITH CHECK (
    auth.uid() = id
  );

-- POLICY: ALLOW AUTHENTICATED USERS TO UPDATE THEIR OWN PROFILE
CREATE POLICY "USERS CAN UPDATE THEIR OWN PROFILE."
  ON public.profiles
  FOR UPDATE
  TO AUTHENTICATED
  USING (
    auth.uid() = id
  );

-- POLICY: ALLOW AUTHENTICATED USERS TO DELETE THEIR OWN PROFILE
CREATE POLICY "USERS CAN DELETE THEIR OWN PROFILE."
  ON public.profiles
  FOR DELETE
  TO AUTHENTICATED
  USING (
    auth.uid() = id
  );

-- FUNCTION: HANDLE NEW USER PROFILE CREATION
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username)
  VALUES (NEW.id, NEW.email);
  RETURN NEW;
END;
$$ LANGUAGE PLPGSQL SECURITY DEFINER;

-- TRIGGER: ON AUTH USER CREATED
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ====================================================================================================
-- ACTIVITIES TABLE
-- ====================================================================================================

-- CREATE THE ACTIVITIES TABLE
CREATE TABLE public.activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  category TEXT,
  time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  amount NUMERIC NOT NULL,
  icon TEXT,
  source_asset_id BIGINT,
  currency TEXT NOT NULL,
  CONSTRAINT FK_USER FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- ENABLE RLS ON THE ACTIVITIES TABLE
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;

-- POLICY: ALLOW AUTHENTICATED USERS TO SELECT THEIR OWN ACTIVITIES
CREATE POLICY "USERS CAN VIEW THEIR OWN ACTIVITIES."
  ON public.activities
  FOR SELECT
  TO AUTHENTICATED
  USING (
    auth.uid() = user_id
  );

-- POLICY: ALLOW AUTHENTICATED USERS TO INSERT THEIR OWN ACTIVITIES
CREATE POLICY "USERS CAN INSERT THEIR OWN ACTIVITIES."
  ON public.activities
  FOR INSERT
  TO AUTHENTICATED
  WITH CHECK (
    auth.uid() = user_id
  );

-- POLICY: ALLOW AUTHENTICATED USERS TO UPDATE THEIR OWN ACTIVITIES
CREATE POLICY "USERS CAN UPDATE THEIR OWN ACTIVITIES."
  ON public.activities
  FOR UPDATE
  TO AUTHENTICATED
  USING (
    auth.uid() = user_id
  );

-- POLICY: ALLOW AUTHENTICATED USERS TO DELETE THEIR OWN ACTIVITIES
CREATE POLICY "USERS CAN DELETE THEIR OWN ACTIVITIES."
  ON public.activities
  FOR DELETE
  TO AUTHENTICATED
  USING (
    auth.uid() = user_id
  );

-- ====================================================================================================
-- ASSET_ITEMS TABLE
-- ====================================================================================================

-- CREATE THE ASSET_ITEMS TABLE
CREATE TABLE public.asset_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  asset_key TEXT NOT NULL,
  name TEXT NOT NULL,
  institution TEXT,
  amount NUMERIC NOT NULL,
  currency TEXT NOT NULL,
  date DATE DEFAULT NOW(),
  remarks TEXT,
  attributes JSONB,
  CONSTRAINT FK_USER_ASSETS FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- ENABLE RLS ON THE ASSET_ITEMS TABLE
ALTER TABLE public.asset_items ENABLE ROW LEVEL SECURITY;

-- POLICY: ALLOW AUTHENTICATED USERS TO SELECT THEIR OWN ASSET ITEMS
CREATE POLICY "USERS CAN VIEW THEIR OWN ASSET ITEMS."
  ON public.asset_items
  FOR SELECT
  TO AUTHENTICATED
  USING (
    auth.uid() = user_id
  );

-- POLICY: ALLOW AUTHENTICATED USERS TO INSERT THEIR OWN ASSET ITEMS
CREATE POLICY "USERS CAN INSERT THEIR OWN ASSET ITEMS."
  ON public.asset_items
  FOR INSERT
  TO AUTHENTICATED
  WITH CHECK (
    auth.uid() = user_id
  );

-- POLICY: ALLOW AUTHENTICATED USERS TO UPDATE THEIR OWN ASSET ITEMS
CREATE POLICY "USERS CAN UPDATE THEIR OWN ASSET ITEMS."
  ON public.asset_items
  FOR UPDATE
  TO AUTHENTICATED
  USING (
    auth.uid() = user_id
  );

-- POLICY: ALLOW AUTHENTICATED USERS TO DELETE THEIR OWN ASSET ITEMS
CREATE POLICY "USERS CAN DELETE THEIR OWN ASSET ITEMS."
  ON public.asset_items
  FOR DELETE
  TO AUTHENTICATED
  USING (
    auth.uid() = user_id
  );